server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalogModule
          uri: http://localhost:8081/
          predicates:
            - Path=/catalog/**
        - id: moviesModule
          uri: http://localhost:8082/
          predicates:
            - Path=/movies/**
        - id: ratingModule
          uri: http://localhost:8083/
          predicates:
            - Path=/ratingsdata/**